# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

global:
  appVersion: 1.13.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-hmnfd
  pullPolicy: IfNotPresent

cray-service:
  type: "Deployment"
  nameOverride: "cray-hmnfd"
  fullnameOverride: "cray-hmnfd"
  replicaCount: 3
  etcdCluster:
    enabled: true
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 10m
        memory: 64Mi
  containers:
    cray-hmnfd:
      name: "cray-hmnfd"
      image:
        repository: "artifactory.algol60.net/csm-docker/stable/cray-hmnfd"
      ports:
        - name: http
          containerPort: 28600
      env:
        - name: SM_URL
          value: "http://cray-smd/hsm/v1"
        - name: INBOUND_SCN_URL
          value: "http://cray-hmnfd/hmi/v1/scn"
        # Remove this to have hmnfd use ETCD.  The etcd operator will
        # provide the hmnfd container with ETCD_HOST and ETCD_PORT to
        # allow it to determine the KV URL.
        # - name: KV_URL
        #   value: "mem:"
      livenessProbe:
        httpGet:
          port: 28600
          path: /hmi/v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        httpGet:
          port: 28600
          path: /hmi/v1/readiness
        initialDelaySeconds: 5
        periodSeconds: 30
      resources:
        limits:
          cpu: "4"
          memory: 2Gi
        requests:
          cpu: 64m
          memory: 512Mi
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: 8082,9092,2181,2379,2380
  ingress:
    enabled: true
    uri: " "
    prefix: /apis/hmnfd
