apiVersion: v2
name: "cray-hms-hmnfd"
version: 4.0.6
description: "Kubernetes resources for cray-hms-hmnfd"
home: "https://github.com/Cray-HPE/hms-hmnfd-charts"
sources:
  - "https://github.com/Cray-HPE/hms-hmnfd"
dependencies:
  - name: cray-service
    version: "~11.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.2"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.23.0"  # update pprof image version below as well
annotations:
  artifacthub.io/images: |-
    - name: cray-hmnfd-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-hmnfd-pprof:1.23.0
  artifacthub.io/license: "MIT"
