# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

global:
  appVersion: 1.19.0
  testVersion: 1.19.0

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-hmnfd
  pullPolicy: IfNotPresent

tests:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-hmnfd-hmth-test
    pullPolicy: IfNotPresent

cray-etcd-base:
  nameOverride: "cray-hmnfd"
  fullnameOverride: "cray-hmnfd"
  etcd:
    enabled: true
    fullnameOverride: "cray-hmnfd-bitnami-etcd"
    nameOverride: "cray-hmnfd-bitnami-tcd"
    disasterRecovery:
      cronjob:
        snapshotsDir: "/snapshots/cray-hmnfd-bitnami-etcd"
        schedule: "0 */1 * * *"
        historyLimit: 1
        snapshotHistoryLimit: 24
    extraEnvVars:
      - name: ETCD_HEARTBEAT_INTERVAL
        value: "4200"
      - name: ETCD_ELECTION_TIMEOUT
        value: "21000"
      - name: ETCD_MAX_SNAPSHOTS
        value: "5"
      - name: ETCD_QUOTA_BACKEND_BYTES
        value: "10737418240"
      - name: ETCD_SNAPSHOT_COUNT
        value: "10000"
      - name: ETCD_SNAPSHOT_HISTORY_LIMIT
        value: "24"
      - name: ETCD_DISABLE_PRESTOP
        value: "yes"
    extraVolumes:
    - configMap:
        defaultMode: 420
        name: cray-hmnfd-bitnami-etcd-config
      name: etcd-config
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 10m
        memory: 64Mi

cray-service:
  type: "Deployment"
  nameOverride: "cray-hmnfd"
  fullnameOverride: "cray-hmnfd"
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - cray-hmnfd
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  etcdWaitContainer: true
  containers:
    cray-hmnfd:
      name: "cray-hmnfd"
      image:
        repository: "artifactory.algol60.net/csm-docker/stable/cray-hmnfd"
      ports:
        - name: http
          containerPort: 28600
      env:
        - name: SM_URL
          value: "http://cray-smd/hsm/v2"
        - name: INBOUND_SCN_URL
          value: "http://cray-hmnfd/hmi/v1/scn"
        # Remove this to have hmnfd use ETCD.  The etcd operator will
        # provide the hmnfd container with ETCD_HOST and ETCD_PORT to
        # allow it to determine the KV URL.
        # - name: KV_URL
        #   value: "mem:"
      livenessProbe:
        httpGet:
          port: 28600
          path: /hmi/v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        httpGet:
          port: 28600
          path: /hmi/v1/readiness
        initialDelaySeconds: 5
        periodSeconds: 30
      resources:
        limits:
          cpu: "4"
          memory: 2Gi
        requests:
          cpu: 64m
          memory: 512Mi
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: 8082,9092,2181,2379,2380
  ingress:
    enabled: true
    uri: " "
    prefix: /apis/hmnfd
